name: Publish

on:
  - push
  # push:
  #   branches:
  #     - master

jobs:
  bundle:
    name: Bundle
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        set -eux
        sudo snap install charm --classic
        sudo snap install charmcraft --classic --channel=latest/candidate
        sudo snap install juju-bundle --classic

    - name: Publish bundle
      env:
        CHARMSTORE_CREDENTIAL: ${{ secrets.CHARMSTORE_CREDENTIAL }}
        CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
      run: |
        set -eux
        echo $CHARMSTORE_CREDENTIAL > ~/.go-cookies
        mkdir -p ~/snap/charmcraft/common/config/
        echo "$CHARMCRAFT_CREDENTIALS" > ~/snap/charmcraft/common/config/charmcraft.credentials
        juju-bundle publish --destructive-mode --serial
